### ISSUE TITLE
uncaught exception: Cannot read property 'mapping' of undefined

### ISSUE THREAD

**Issue by fennsen64** [ioBroker/ioBroker.pimatic#1]
Hi Bluefox, this is really THE plugin I've waited for!!!

But when starting it seems to have issues with defied variables (all kinds: text, bolean etc.) when tries to map. My pimatic Version is the version (0.9.5).
When i look into the pimatic.0 object list, only the first device in my pimatic list is loaded (but also without any value)

Here is the log from ioBroker:
```
pimatic.0	2017-03-24 17:57:57.726	info	disconnected
pimatic.0	2017-03-24 17:57:57.719	error	at Decoder.add (/opt/iobroker/node_modules/iobroker.pimatic/node_modules/socket.io-client/node_modules/socket.io-parser/index.js:246:12)
pimatic.0	2017-03-24 17:57:57.719	error	at Decoder.Emitter.emit (/opt/iobroker/node_modules/iobroker.pimatic/node_modules/socket.io-client/node_modules/socket.io-parser/node_modules/component-emitter/index.js:134:20)
pimatic.0	2017-03-24 17:57:57.719	error	at Decoder. (/opt/iobroker/node_modules/iobroker.pimatic/node_modules/socket.io-client/node_modules/component-bind/index.js:21:15)
pimatic.0	2017-03-24 17:57:57.719	error	at Manager.ondecoded (/opt/iobroker/node_modules/iobroker.pimatic/node_modules/socket.io-client/lib/manager.js:332:8)
pimatic.0	2017-03-24 17:57:57.719	error	at Manager.Emitter.emit (/opt/iobroker/node_modules/iobroker.pimatic/node_modules/socket.io-client/node_modules/component-emitter/index.js:133:20)
pimatic.0	2017-03-24 17:57:57.719	error	at Manager. (/opt/iobroker/node_modules/iobroker.pimatic/node_modules/socket.io-client/node_modules/component-bind/index.js:21:15)
pimatic.0	2017-03-24 17:57:57.719	error	at Socket.onpacket (/opt/iobroker/node_modules/iobroker.pimatic/node_modules/socket.io-client/lib/socket.js:228:12)
pimatic.0	2017-03-24 17:57:57.719	error	at Socket.onevent (/opt/iobroker/node_modules/iobroker.pimatic/node_modules/socket.io-client/lib/socket.js:270:10)
pimatic.0	2017-03-24 17:57:57.719	error	at Socket.Emitter.emit (/opt/iobroker/node_modules/iobroker.pimatic/node_modules/socket.io-client/node_modules/component-emitter/index.js:133:20)
pimatic.0	2017-03-24 17:57:57.719	error	at Socket. (/opt/iobroker/node_modules/iobroker.pimatic/main.js:512:50)
pimatic.0	2017-03-24 17:57:57.719	error	TypeError: Cannot read property 'mapping' of undefined
pimatic.0	2017-03-24 17:57:57.712	error	uncaught exception: Cannot read property 'mapping' of undefined
pimatic.0	2017-03-24 17:57:57.699	warn	Unknown state: pimatic.0.devices.dewpoint-diff-trigger-AZ
pimatic.0	2017-03-24 17:57:57.699	warn	Unknown state: pimatic.0.devices.pump-available-master
pimatic.0	2017-03-24 17:57:57.699	warn	Unknown state: pimatic.0.devices.hue-scene-lichter-kaminraum-tag
pimatic.0	2017-03-24 17:57:57.699	warn	Unknown state: pimatic.0.devices.hue-scene-lichter-treppe-lila
pimatic.0	2017-03-24 17:57:57.698	warn	Unknown state: pimatic.0.devices.hue-scene-lichter-treppe-hell
pimatic.0	2017-03-24 17:57:57.698	warn	Unknown state: pimatic.0.devices.hue-scene-lichter-treppe-ambiente
pimatic.0	2017-03-24 17:57:57.698	warn	Unknown state: pimatic.0.devices.hue-scene-lichter-ALARM
pimatic.0	2017-03-24 17:57:57.697	warn	Unknown state: pimatic.0.devices.panikmode
pimatic.0	2017-03-24 17:57:57.696	warn	Unknown state: pimatic.0.devices.testvariable3
pimatic.0	2017-03-24 17:57:57.696	warn	Unknown state: pimatic.0.devices.hue-scene-lichter-ambiente-kaminfeuer
pimatic.0	2017-03-24 17:57:57.696	warn	Unknown state: pimatic.0.devices.hue-scene-lichter-lesen
pimatic.0	2017-03-24 17:57:57.696	warn	Unknown state: pimatic.0.devices.hue-scene-lichter-ambiente-blau
pimatic.0	2017-03-24 17:57:57.696	warn	Unknown state: pimatic.0.devices.hue-user
pimatic.0	2017-03-24 17:57:57.695	warn	Unknown state: pimatic.0.devices.hue-scene-lichter-stereomodus
pimatic.0	2017-03-24 17:57:57.695	warn	Unknown state: pimatic.0.devices.stereo-modus
pimatic.0	2017-03-24 17:57:57.695	warn	Unknown state: pimatic.0.devices.hue-scene-lichter-discomodus
pimatic.0	2017-03-24 17:57:57.695	warn	Unknown state: pimatic.0.devices.hue-scene-lichter-relax
pimatic.0	2017-03-24 17:57:57.694	warn	Unknown state: pimatic.0.devices.hue-scene-lichter-normal
pimatic.0	2017-03-24 17:57:57.693	warn	Unknown state: pimatic.0.devices.hue-scene-lichter-security-standard
pimatic.0	2017-03-24 17:57:57.693	warn	Unknown state: pimatic.0.devices.hue-scene-tv-dunkel
pimatic.0	2017-03-24 17:57:57.693	warn	Unknown state: pimatic.0.devices.hue-scene-tv-hell
pimatic.0	2017-03-24 17:57:57.693	warn	Unknown state: pimatic.0.devices.s
pimatic.0	2017-03-24 17:57:57.693	warn	Unknown state: pimatic.0.devices.h
pimatic.0	2017-03-24 17:57:57.692	warn	Unknown state: pimatic.0.devices.c
pimatic.0	2017-03-24 17:57:57.692	warn	Unknown state: pimatic.0.devices.d
pimatic.0	2017-03-24 17:57:57.692	warn	Unknown state: pimatic.0.devices.disco-modus
pimatic.0	2017-03-24 17:57:57.692	warn	Unknown state: pimatic.0.devices.cams-aussen-routine-running
pimatic.0	2017-03-24 17:57:57.691	warn	Unknown state: pimatic.0.devices.cams-innen-routine-running
pimatic.0	2017-03-24 17:57:57.691	warn	Unknown state: pimatic.0.devices.cams-innen-routine
pimatic.0	2017-03-24 17:57:57.691	warn	Unknown state: pimatic.0.devices.cams-aussen-routine
pimatic.0	2017-03-24 17:57:57.691	warn	Unknown state: pimatic.0.devices.simulationmode
pimatic.0	2017-03-24 17:57:57.691	warn	Unknown state: pimatic.0.devices.lichter-routine
pimatic.0	2017-03-24 17:57:57.690	warn	Unknown state: pimatic.0.devices.dewpoint-diff-trigger
pimatic.0	2017-03-24 17:57:57.690	warn	Unknown state: pimatic.0.devices.ospi-hitze-bewaesserung-already-run-today
pimatic.0	2017-03-24 17:57:57.690	warn	Unknown state: pimatic.0.devices.ospi-hitze-bewaesserung-15min
pimatic.0	2017-03-24 17:57:57.690	warn	Unknown state: pimatic.0.devices.ospi-hitze-bewaesserung-30min
pimatic.0	2017-03-24 17:57:57.690	warn	Unknown state: pimatic.0.devices.alarmmode
pimatic.0	2017-03-24 17:57:57.689	warn	Unknown state: pimatic.0.devices.anybodyhome
pimatic.0	2017-03-24 17:57:57.688	warn	Unknown state: pimatic.0.devices.lichter-routine-running
pimatic.0	2017-03-24 17:57:57.189	info	connected
pimatic.0	2017-03-24 17:57:54.663	info	starting. Version 0.1.1 in /opt/iobroker/node_modules/iobroker.pimatic, node: v4.7.0
host.mon-pi	2017-03-24 17:57:52.316	info	instance system.adapter.pimatic.0 started with pid 27681
host.mon-pi	2017-03-24 17:57:22.301	info	Restart adapter system.adapter.pimatic.0 because enabled```

**Comment by GermanBluefox** [comment]
https://github.com/ioBroker/ioBroker.pimatic/commit/c43bdf6a81f069042dc3cc59622682ff03be121f

**Comment by GermanBluefox** [comment]
Please test.

**Comment by fennsen64** [comment]
THX for the very fast fix. Just installed the update and it seems to work (I can see all devices and switch them from ioBroker). Great work!!
Is it planned to also include pure variables here as a second class beside the devices (of course not active)? This would be really great because a lot of my rules are based on 'logical' or expression variables.
THX again

**Comment by fennsen64** [comment]
Ok, after some more testings: switching (switch devices) from ioBroker to pimatic doesn't work. 
There seems to be an issue with the different formats of boolean's

The 'translated pimatic' value in ioBroker objects for a switch device is 'off(false) / on(true)'. But in pimatic this boolean seems not to be interpreted right when I switch such a device from ioBroker:
Pimatix log:
error [pimatic]: Exprected state to be boolean, was: 0
error [pimatic]: Exprected state to be boolean, was: 1

Other way round (switching in pimatic -> updates value in ioBroker correctly) is working

**Comment by GermanBluefox** [comment]
Please check new version: https://github.com/ioBroker/ioBroker.pimatic/blob/master/main.js#L58

**Comment by fennsen64** [comment]
Great.
After update to 1.3 it also works with the jqui Radiobutton.
Thanks!!
